urls = (
    '/', 'application.controllers.main.index.Index',
    '/404', 'application.controllers.main.notfound.NotFound',
    '/500', 'application.controllers.main.internalerror.InternalError',
    '/login', 'application.controllers.main.login.Login',
    '/logout', 'application.controllers.main.logout.Logout',
    '/profile', 'application.controllers.main.profile.Profile',
    '/users', 'application.controllers.users.index.Index',
    '/users/printer', 'application.controllers.users.printer.Printer',
    '/users/view/(.+)', 'application.controllers.users.view.View',
    '/users/edit/(.+)', 'application.controllers.users.edit.Edit',
    '/users/delete/(.+)', 'application.controllers.users.delete.Delete',
    '/users/insert', 'application.controllers.users.insert.Insert',
    '/users/change_pwd', 'application.controllers.users.change_pwd.Change_pwd',
    '/logs', 'application.controllers.logs.index.Index',
    '/logs/printer', 'application.controllers.logs.printer.Printer',
    '/logs/view/(.+)', 'application.controllers.logs.view.View',
    '/pages_urls', 'application.controllers.pages_urls.index.Index',
    '/pages_urls/view/(.+)', 'application.controllers.pages_urls.view.View',
    '/pages_urls/edit/(.+)', 'application.controllers.pages_urls.edit.Edit',
    '/pages_urls/delete/(.+)', 'application.controllers.pages_urls.delete.Delete',
    '/pages_urls/insert', 'application.controllers.pages_urls.insert.Insert',

    '/productos', 'application.controllers.productos.index.Index',
    '/productos/view/(.+)', 'application.controllers.productos.view.View',
    '/productos/edit/(.+)', 'application.controllers.productos.edit.Edit',
    '/productos/delete/(.+)', 'application.controllers.productos.delete.Delete',
    '/productos/insert/?', 'application.controllers.productos.insert.Insert',
    '/productos/import/?', 'application.controllers.productos.import_file.Import_File',
    '/api_productos/?', 'application.api.productos.api_productos.Api_productos',
)
